### ISSUE TITLE
C-VLDA

### ISSUE THREAD

**Issue by Codeei** [zeng-ziyin/U-Next#3]
你好，我是看了LACV-Net那篇论文过来的，在LACV_UNet我只找到了C-VLDA的def，没有看到调用，请问C-VLDA的调用体现在什么地方呢？

**Comment by zeng-ziyin** [comment]
不好意思，参照unext的论文，我们在unext里面屏蔽了除了局部特征聚合以外的模块。我们过几天会上传一个完整的lacv-net代码发自我的iPhone------------------ Original ------------------From: Codeei  ***@***.***>Date: Sat,Dec 30,2023 4:45 PMTo: zeng-ziyin/U-Next ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [zeng-ziyin/U-Next] C-VLDA (Issue #3)
你好，我是看了LACV-Net那篇论文过来的，在LACV_UNet我只找到了C-VLDA的def，没有看到调用，请问C-VLDA的调用体现在什么地方呢？

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/zeng-ziyin/U-Next/issues/3",
"url": "https://github.com/zeng-ziyin/U-Next/issues/3",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zeng-ziyin** [comment]
我们已经上传了完整的LACV-Net.py文件

**Comment by Codeei** [comment]
非常感谢 :）
